# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
  - 1.3.1
notifications:
  email: false
before_install:
  - julia -e 'haskey(Pkg.installed(), "SpecialFunctions") || Pkg.add("SpecialFunctions")'
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Libm"); Pkg.test("Libm"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Libm")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Libm")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
